export enum BankTransferState {
    STATE_SCHEDULED = 100,
    STATE_PROCESSING = 101,
    STATE_AWAITING_BAMBORA_UPDATE = 102,
    STATE_AWAITING_BALANCE_UPDATE = 103,
    STATE_SUCCESS = 104,
    STATE_CANCELLED = 144,
}
